steps:
  # 1. Build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/clinicalchain-repo/inventory-api:$_COMMIT_SHA', './inventory-api']

  # 2. Push the container image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/clinicalchain-repo/inventory-api:$_COMMIT_SHA']

  # 3. Deploy the container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'inventory-api'
      - '--image'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/clinicalchain-repo/inventory-api:$_COMMIT_SHA'
      - '--region'
      - 'us-central1'
      - '--allow-unauthenticated'

images:
  - 'us-central1-docker.pkg.dev/$PROJECT_ID/clinicalchain-repo/inventory-api:$_COMMIT_SHA'
